from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def replace_once(text, pattern, replacement, path, flags=re.S):
    updated, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise RuntimeError(f"{path}: expected one replacement for {pattern!r}, got {count}")
    return updated


def update_profile(path, intro, body, meta):
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    text = replace_once(text, r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{meta}">', path)
    text = replace_once(text, r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{meta}">', path)
    text = replace_once(text, r'<p class="consultant-intro">.*?</p>', f'<p class="consultant-intro">{intro}</p>', path)
    pattern = r'(<section class="profile-content"><div class="container profile-content-grid"><div>).*?(</div><aside class="profile-sidebar">)'
    text = replace_once(text, pattern, lambda m: m.group(1) + body + m.group(2), path)
    p.write_text(text, encoding="utf-8")


def update_directory_card(path, doctor_name, focus):
    p = ROOT / path
    text = p.read_text(encoding="utf-8")
    pattern = rf'(<article class="doctor-directory-card[^>]*data-name="{re.escape(doctor_name)}".*?</article>)'
    match = re.search(pattern, text, flags=re.S)
    if not match:
        raise RuntimeError(f"{path}: doctor card not found for {doctor_name}")
    block = match.group(1)
    block2, count = re.subn(r'<p class="doctor-directory-card__focus">.*?</p>', f'<p class="doctor-directory-card__focus">{focus}</p>', block, count=1, flags=re.S)
    if count != 1:
        raise RuntimeError(f"{path}: focus paragraph not found for {doctor_name}")
    text = text[:match.start()] + block2 + text[match.end():]
    p.write_text(text, encoding="utf-8")


EN = {
    "doctors/dr-kashmira-pawar-jayprakash.html": {
        "meta": "Meet Dr. Kashmira Pawar Jayprakash, Specialist Pediatric Dentist at Silwadi Dental Center in Abu Dhabi, with over nine years of clinical experience.",
        "intro": "Dr. Kashmira Pawar Jayprakash is a Specialist Pediatric Dentist with over nine years of clinical experience. Her approach centres on prevention, early intervention and age-appropriate care, with particular attention to children who may feel anxious or require additional support during dental treatment.",
        "body": '<section class="profile-section"><h2>Clinical focus</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>Preventive &amp; restorative pediatric care</strong><span>Examinations, preventive care, fluoride, sealants, restorations and pediatric crowns based on clinical need.</span></div><div class="clinical-focus-item"><strong>Pulp therapy &amp; dental trauma</strong><span>Pulpotomy, pulpectomy and assessment of dental injuries and urgent pediatric concerns.</span></div><div class="clinical-focus-item"><strong>Anxiety &amp; special-care dentistry</strong><span>Behavioral guidance and nitrous oxide conscious sedation where clinically appropriate, including individualized care for children with additional needs.</span></div><div class="clinical-focus-item"><strong>Early guidance</strong><span>Space maintenance, interceptive appliances, oral-habit counselling and practical guidance for parents and caregivers.</span></div></div></section><section class="profile-section"><h2>Education &amp; professional background</h2><ul class="qualification-list"><li>BDS, D.Y. Patil University</li><li>MDS in Pediatric Dentistry, RGUHS</li><li>Certifications in Nitrous Oxide Conscious Sedation, PALS and BLS</li><li>Published researcher and member of the IDA and IAPD</li></ul></section><section class="profile-section"><h2>Approach to care</h2><p>Dr. Kashmira emphasizes prevention, education and clear communication with both children and their families. Treatment is planned around the child’s clinical needs, age and level of cooperation.</p></section><section class="profile-section"><h2>Related care</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../services.html#pedodontics">Pediatric Dentistry <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">View treatments <span>→</span></a></div></section>'
    },
    "doctors/dr-nasr-keshkiea.html": {
        "meta": "Meet Dr. Nasr Keshkiea, General Dentist at Silwadi Dental Center in Abu Dhabi, with over eight years of clinical experience and postgraduate prosthodontic training.",
        "intro": "Dr. Nasr Keshkiea is a DOH-licensed General Dentist with over eight years of clinical experience across restorative, prosthodontic, endodontic and aesthetic dentistry. His postgraduate training in removable prosthodontics supports a strong interest in functional rehabilitation and restorative treatment planning.",
        "body": '<section class="profile-section"><h2>Clinical focus</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>Prosthodontic rehabilitation</strong><span>Complete and partial dentures, crowns, bridges and restorative planning for patients requiring functional rehabilitation.</span></div><div class="clinical-focus-item"><strong>Restorative &amp; aesthetic dentistry</strong><span>Anterior and posterior composite restorations, veneers and in-office teeth whitening.</span></div><div class="clinical-focus-item"><strong>Endodontic care</strong><span>Routine root canal treatment using rotary instrumentation within general dental practice.</span></div><div class="clinical-focus-item"><strong>General &amp; emergency care</strong><span>Examinations, preventive care, simple extractions and assessment of urgent dental concerns.</span></div></div></section><section class="profile-section"><h2>Education &amp; professional background</h2><ul class="qualification-list"><li>Bachelor’s Degree in Dentistry, Damascus University, 2017</li><li>Master of Science in Removable Prosthodontics, Hama University, 2022</li><li>Syrian Board Certification in Removable Prosthodontics, 2023</li><li>Former clinical supervisor in removable prosthodontics at Hama University and Damascus University</li></ul></section><section class="profile-section"><h2>Languages &amp; approach</h2><p>Dr. Nasr speaks Arabic and English. He focuses on clear communication, individualized treatment planning and coordinating restorative care around each patient’s functional and aesthetic needs.</p></section><section class="profile-section"><h2>Related care</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/general-dentistry.html">General Dentistry <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">View treatments <span>→</span></a></div></section>'
    },
    "doctors/dr-ehab-hassouneh.html": {
        "meta": "Meet Dr. Ehab Hassouneh, General Dentist at Silwadi Dental Center in Abu Dhabi, providing restorative, digital, pediatric and preventive dental care.",
        "intro": "Dr. Ehab Hassouneh is a General Dentist providing care for adult and pediatric patients. He combines restorative and preventive dentistry with digital workflows and clear treatment planning, with a focus on helping patients understand their options at each stage of care.",
        "body": '<section class="profile-section"><h2>Clinical focus</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>Restorative &amp; aesthetic dentistry</strong><span>Direct composite restorations, professional dental bleaching and restorative treatment planning.</span></div><div class="clinical-focus-item"><strong>Digital dentistry &amp; prosthodontics</strong><span>Digital intra-oral assessment, CAD/CAM scanner workflows and fixed or removable prosthodontic care within general practice.</span></div><div class="clinical-focus-item"><strong>Endodontic &amp; pediatric care</strong><span>Routine root canal treatment together with preventive and restorative dental care for children.</span></div><div class="clinical-focus-item"><strong>Preventive care &amp; simple oral surgery</strong><span>Radiographic assessment, routine cleaning, oral-health education and simple tooth extractions where indicated.</span></div></div></section><section class="profile-section"><h2>Education &amp; professional background</h2><ul class="qualification-list"><li>Bachelor of Dental Surgery from RAK College of Dental Sciences</li><li>Dental internship training across restorative, endodontic, prosthetic and simple surgical rotations</li><li>Certifications in Nitrous Oxide Conscious Sedation and Professional Dental Bleaching</li><li>Previous experience in healthcare quality control and insurance coding in Abu Dhabi</li></ul></section><section class="profile-section"><h2>Approach to care</h2><p>Dr. Ehab places emphasis on attentive communication and individualized treatment planning. His consultations focus on understanding the patient’s concerns, explaining findings clearly and supporting long-term oral health.</p></section><section class="profile-section"><h2>Related care</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/general-dentistry.html">General Dentistry <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">View treatments <span>→</span></a></div></section>'
    },
    "doctors/dr-nachiket-shah.html": {
        "meta": "Meet Dr. Nachiket Shah, Specialist Periodontist with implant privilege at Silwadi Dental Center in Abu Dhabi, with more than 14 years of clinical experience.",
        "intro": "Dr. Nachiket Shah is a DOH-licensed Specialist Periodontist with implant privilege and more than 14 years of clinical experience across India and the UAE. His practice focuses on periodontal treatment, implant dentistry, tissue regeneration and selected oral surgical procedures.",
        "body": '<section class="profile-section"><h2>Clinical focus</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>Periodontal treatment</strong><span>Assessment and surgical management of periodontal conditions, including procedures for gum recession and crown lengthening where indicated.</span></div><div class="clinical-focus-item"><strong>Implant dentistry</strong><span>Single-tooth, partial and full-arch implant treatment planning within his granted implant privilege.</span></div><div class="clinical-focus-item"><strong>Bone &amp; soft-tissue procedures</strong><span>Socket preservation, localized ridge augmentation, bone grafting and connective-tissue grafting.</span></div><div class="clinical-focus-item"><strong>Laser-assisted &amp; oral surgical care</strong><span>Use of Diode and Er:YAG laser techniques for selected periodontal and soft-tissue procedures, together with surgical extractions where clinically indicated.</span></div></div></section><section class="profile-section"><h2>Education &amp; professional background</h2><ul class="qualification-list"><li>BDS, 2001</li><li>MDS in Periodontology and Implantology, 2009</li><li>2nd Level University Master’s in Oral Surgery &amp; Implantology, UniCamillus, Rome</li><li>MSc in Quality and Safety in Healthcare Management, Royal College of Surgeons in Ireland</li></ul></section><section class="profile-section"><h2>Languages &amp; approach</h2><p>Dr. Nachiket communicates in English, Hindi, Gujarati and Marathi, with working Arabic. He emphasizes clear treatment education, careful surgical planning and patient comfort throughout periodontal and implant care.</p></section><section class="profile-section"><h2>Related care</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/dental-implants.html">Dental Implants <span>→</span></a><a class="profile-treatment-link" href="../services.html#periodontics">Periodontics <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">View treatments <span>→</span></a></div></section>'
    },
    "doctors/dr-sara-ismail.html": {
        "meta": "Meet Dr. Sara Ismail, General Dentist at Silwadi Dental Center in Abu Dhabi, with training in aesthetic, restorative, endodontic and pediatric dentistry.",
        "intro": "Dr. Sara Ismail is a General Dentist with four years of clinical experience and additional training in aesthetic and endodontic dentistry. Her clinical interests include restorative and aesthetic care, root canal treatment, pediatric dentistry and preventive treatment.",
        "body": '<section class="profile-section"><h2>Clinical focus</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>Restorative &amp; aesthetic dentistry</strong><span>Anterior and posterior composite restorations, veneers, in-office teeth whitening and CAD/CAM restorations.</span></div><div class="clinical-focus-item"><strong>Endodontic care</strong><span>Root canal treatment using contemporary rotary techniques, with additional training in microscopic endodontics and 3D imaging.</span></div><div class="clinical-focus-item"><strong>Pediatric dentistry</strong><span>Preventive and restorative care for children, including pulp therapy, stainless-steel crowns, sealants, fluoride and habit counselling.</span></div><div class="clinical-focus-item"><strong>Preventive &amp; emergency care</strong><span>Routine scale and polish, simple extractions, abscess management and assessment of urgent dental concerns.</span></div></div></section><section class="profile-section"><h2>Education &amp; professional background</h2><ul class="qualification-list"><li>DDS from Ajman University</li><li>Dental Internship Program, Ajman University</li><li>Diploma in Advanced Esthetic Dentistry, Mastery Academy, Dubai</li><li>Additional Fellowship training in Successful Endodontic Practice under Prof. Dr. Talal Al Nahlawi</li></ul></section><section class="profile-section"><h2>Languages &amp; approach</h2><p>Dr. Sara speaks Arabic and English. She places emphasis on clear communication, patient comfort and treatment plans tailored to the clinical needs of adults and children.</p></section><section class="profile-section"><h2>Related care</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/cosmetic-dentistry.html">Cosmetic Dentistry <span>→</span></a><a class="profile-treatment-link" href="../treatments/general-dentistry.html">General Dentistry <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">View treatments <span>→</span></a></div></section>'
    },
}

AR = {
    "ar/doctors/dr-kashmira-pawar-jayprakash.html": {
        "meta": "تعرّفوا إلى د. كاشميرا باوار جايبراكاش، أخصائية طب أسنان الأطفال في مركز سلوادي بأبوظبي، بخبرة سريرية تزيد عن تسع سنوات.",
        "intro": "د. كاشميرا باوار جايبراكاش أخصائية في طب أسنان الأطفال ولديها أكثر من تسع سنوات من الخبرة السريرية. تركز في عملها على الوقاية والتدخل المبكر والرعاية المناسبة لعمر الطفل، مع اهتمام خاص بالأطفال الذين يشعرون بالقلق أو يحتاجون إلى دعم إضافي أثناء العلاج.",
        "body": '<section class="profile-section"><h2>التركيز السريري</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>الوقاية والترميم للأطفال</strong><span>الفحوصات والعناية الوقائية والفلورايد والسيلانت والترميمات وتيجان الأطفال وفق الحاجة السريرية.</span></div><div class="clinical-focus-item"><strong>علاج لب الأسنان وإصابات الأسنان</strong><span>البتر اللبي واستئصال اللب وتقييم إصابات الأسنان والحالات الطارئة لدى الأطفال.</span></div><div class="clinical-focus-item"><strong>القلق والرعاية الخاصة</strong><span>أساليب التوجيه السلوكي والتهدئة الواعية بأكسيد النيتروز عند ملاءمتها سريرياً، مع رعاية فردية للأطفال ذوي الاحتياجات الإضافية.</span></div><div class="clinical-focus-item"><strong>التوجيه المبكر</strong><span>حافظات المسافة والأجهزة الاعتراضية وإرشاد العادات الفموية وتوجيه الوالدين ومقدمي الرعاية.</span></div></div></section><section class="profile-section"><h2>التعليم والخلفية المهنية</h2><ul class="qualification-list"><li>بكالوريوس طب وجراحة الأسنان، جامعة D.Y. Patil</li><li>ماجستير في طب أسنان الأطفال، RGUHS</li><li>شهادات في التهدئة الواعية بأكسيد النيتروز وPALS وBLS</li><li>لها أبحاث منشورة وعضوية في IDA وIAPD</li></ul></section><section class="profile-section"><h2>نهج الرعاية</h2><p>تركز د. كاشميرا على الوقاية والتثقيف والتواصل الواضح مع الطفل وعائلته، مع تخطيط العلاج وفق العمر والحاجة السريرية ومستوى تعاون الطفل.</p></section><section class="profile-section"><h2>الرعاية ذات الصلة</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../../services.html#pedodontics">طب أسنان الأطفال <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">عرض العلاجات <span>→</span></a></div></section>'
    },
    "ar/doctors/dr-nasr-keshkiea.html": {
        "meta": "تعرّفوا إلى د. نصر كشكية، طبيب أسنان عام في مركز سلوادي بأبوظبي، بخبرة سريرية تزيد عن ثماني سنوات وتدريب دراسات عليا في التعويضات السنية.",
        "intro": "د. نصر كشكية طبيب أسنان عام مرخص من دائرة الصحة - أبوظبي ولديه أكثر من ثماني سنوات من الخبرة السريرية في طب الأسنان الترميمي والتعويضات السنية وعلاج الجذور والتجميل. ويدعم تدريبه المتقدم في التعويضات المتحركة اهتمامه بإعادة التأهيل الوظيفي وخطط العلاج الترميمية.",
        "body": '<section class="profile-section"><h2>التركيز السريري</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>التعويضات وإعادة التأهيل</strong><span>الأطقم الكاملة والجزئية والتيجان والجسور والتخطيط الترميمي لاستعادة الوظيفة.</span></div><div class="clinical-focus-item"><strong>الترميم والتجميل</strong><span>ترميمات الكومبوزت الأمامية والخلفية والقشور وتبييض الأسنان داخل العيادة.</span></div><div class="clinical-focus-item"><strong>علاج الجذور</strong><span>علاج جذور الأسنان الروتيني باستخدام أدوات دوارة ضمن نطاق ممارسة طب الأسنان العام.</span></div><div class="clinical-focus-item"><strong>الرعاية العامة والطارئة</strong><span>الفحوصات والوقاية والخلع البسيط وتقييم الحالات السنية العاجلة.</span></div></div></section><section class="profile-section"><h2>التعليم والخلفية المهنية</h2><ul class="qualification-list"><li>بكالوريوس طب الأسنان، جامعة دمشق، 2017</li><li>ماجستير العلوم في التعويضات السنية المتحركة، جامعة حماة، 2022</li><li>البورد السوري في التعويضات السنية المتحركة، 2023</li><li>عمل سابقاً مشرفاً سريرياً في التعويضات المتحركة بجامعتي حماة ودمشق</li></ul></section><section class="profile-section"><h2>اللغات ونهج الرعاية</h2><p>يتحدث د. نصر العربية والإنجليزية، ويركز على التواصل الواضح ووضع خطة علاج فردية تراعي الاحتياجات الوظيفية والجمالية لكل مريض.</p></section><section class="profile-section"><h2>الرعاية ذات الصلة</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/general-dentistry.html">طب الأسنان العام <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">عرض العلاجات <span>→</span></a></div></section>'
    },
    "ar/doctors/dr-ehab-hassouneh.html": {
        "meta": "تعرّفوا إلى د. إيهاب حسونة، طبيب أسنان عام في مركز سلوادي بأبوظبي، ويقدم رعاية ترميمية ورقمية ووقائية للبالغين والأطفال.",
        "intro": "د. إيهاب حسونة طبيب أسنان عام يقدم الرعاية للبالغين والأطفال. حصل على بكالوريوس جراحة الأسنان من كلية رأس الخيمة لطب الأسنان، ويجمع في ممارسته بين طب الأسنان الترميمي والوقائي وسير العمل الرقمي مع شرح واضح لخيارات العلاج.",
        "body": '<section class="profile-section"><h2>التركيز السريري</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>الترميم والتجميل</strong><span>ترميمات الكومبوزت المباشرة وتبييض الأسنان المهني والتخطيط للعلاجات الترميمية.</span></div><div class="clinical-focus-item"><strong>طب الأسنان الرقمي والتعويضات</strong><span>الفحص الرقمي داخل الفم وسير عمل ماسحات CAD/CAM والتعويضات الثابتة والمتحركة ضمن نطاق الممارسة العامة.</span></div><div class="clinical-focus-item"><strong>علاج الجذور ورعاية الأطفال</strong><span>علاج الجذور الروتيني إلى جانب الرعاية الوقائية والترميمية للأطفال.</span></div><div class="clinical-focus-item"><strong>الوقاية والخلع البسيط</strong><span>التقييم بالأشعة والتنظيف الروتيني والتثقيف بصحة الفم والخلع البسيط عند وجود داعٍ سريري.</span></div></div></section><section class="profile-section"><h2>التعليم والخلفية المهنية</h2><ul class="qualification-list"><li>بكالوريوس جراحة الأسنان من كلية رأس الخيمة لطب الأسنان</li><li>تدريب امتياز شمل الترميم وعلاج الجذور والتعويضات والإجراءات الجراحية البسيطة</li><li>شهادات في التهدئة الواعية بأكسيد النيتروز وتبييض الأسنان المهني</li><li>خبرة سابقة في ضبط الجودة والترميز التأميني في القطاع الصحي بأبوظبي</li></ul></section><section class="profile-section"><h2>نهج الرعاية</h2><p>يركز د. إيهاب على التواصل المتأني ووضع خطة علاج فردية، مع شرح النتائج السريرية والخيارات المتاحة بصورة واضحة ودعم صحة الفم على المدى الطويل.</p></section><section class="profile-section"><h2>الرعاية ذات الصلة</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/general-dentistry.html">طب الأسنان العام <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">عرض العلاجات <span>→</span></a></div></section>'
    },
    "ar/doctors/dr-nachiket-shah.html": {
        "meta": "تعرّفوا إلى د. ناشيكيت شاه، أخصائي أمراض اللثة مع امتياز زراعة الأسنان في مركز سلوادي بأبوظبي، بخبرة سريرية تتجاوز 14 عاماً.",
        "intro": "د. ناشيكيت شاه أخصائي أمراض لثة مرخص من دائرة الصحة - أبوظبي مع امتياز زراعة الأسنان، ولديه أكثر من 14 عاماً من الخبرة السريرية في الهند والإمارات. يركز عمله على علاج أمراض اللثة وزراعة الأسنان وتجديد الأنسجة والإجراءات الجراحية المختارة.",
        "body": '<section class="profile-section"><h2>التركيز السريري</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>علاج أمراض اللثة</strong><span>تقييم وعلاج حالات اللثة، بما في ذلك الإجراءات الجراحية لانحسار اللثة وإطالة التاج عند الحاجة.</span></div><div class="clinical-focus-item"><strong>زراعة الأسنان</strong><span>تخطيط زراعة سن واحد أو عدة أسنان أو إعادة التأهيل بالقوس الكامل ضمن امتيازات الزراعة الممنوحة له.</span></div><div class="clinical-focus-item"><strong>العظم والأنسجة الرخوة</strong><span>الحفاظ على السنخ وزيادة عرض الحافة والترقيع العظمي وترقيع النسيج الضام.</span></div><div class="clinical-focus-item"><strong>الليزر والجراحة الفموية</strong><span>استخدام تقنيات ليزر Diode وEr:YAG في إجراءات مختارة للثة والأنسجة الرخوة، إضافة إلى الخلع الجراحي عند وجود داعٍ سريري.</span></div></div></section><section class="profile-section"><h2>التعليم والخلفية المهنية</h2><ul class="qualification-list"><li>بكالوريوس طب وجراحة الأسنان، 2001</li><li>ماجستير في أمراض اللثة وزراعة الأسنان، 2009</li><li>ماجستير جامعي من المستوى الثاني في جراحة الفم وزراعة الأسنان، UniCamillus، روما</li><li>ماجستير العلوم في إدارة الجودة والسلامة في الرعاية الصحية، الكلية الملكية للجراحين في إيرلندا</li></ul></section><section class="profile-section"><h2>اللغات ونهج الرعاية</h2><p>يتواصل د. ناشيكيت بالإنجليزية والهندية والغوجاراتية والماراثية، إضافة إلى مستوى عملي في العربية. ويركز على شرح العلاج بوضوح والتخطيط الجراحي الدقيق وراحة المريض أثناء رعاية اللثة والزراعة.</p></section><section class="profile-section"><h2>الرعاية ذات الصلة</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/dental-implants.html">زراعة الأسنان <span>→</span></a><a class="profile-treatment-link" href="../../services.html#periodontics">أمراض اللثة <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">عرض العلاجات <span>→</span></a></div></section>'
    },
    "ar/doctors/dr-sara-ismail.html": {
        "meta": "تعرّفوا إلى د. سارة إسماعيل، طبيبة أسنان عامة في مركز سلوادي بأبوظبي، مع تدريب في طب الأسنان التجميلي والترميمي وعلاج الجذور ورعاية الأطفال.",
        "intro": "د. سارة إسماعيل طبيبة أسنان عامة لديها أربع سنوات من الخبرة السريرية وتدريب إضافي في طب الأسنان التجميلي وعلاج الجذور. تشمل اهتماماتها السريرية الترميمات التجميلية وعلاج الجذور ورعاية أسنان الأطفال والعلاج الوقائي.",
        "body": '<section class="profile-section"><h2>التركيز السريري</h2><div class="clinical-focus-grid"><div class="clinical-focus-item"><strong>الترميم والتجميل</strong><span>ترميمات الكومبوزت الأمامية والخلفية والقشور وتبييض الأسنان وترميمات CAD/CAM.</span></div><div class="clinical-focus-item"><strong>علاج الجذور</strong><span>علاج جذور الأسنان بتقنيات دوارة حديثة، مع تدريب إضافي في علاج الجذور بالمجهر والتصوير ثلاثي الأبعاد.</span></div><div class="clinical-focus-item"><strong>طب أسنان الأطفال</strong><span>الرعاية الوقائية والترميمية للأطفال، بما في ذلك علاج اللب والتيجان المعدنية والسيلانت والفلورايد وإرشاد العادات.</span></div><div class="clinical-focus-item"><strong>الوقاية والطوارئ</strong><span>التنظيف الروتيني والخلع البسيط وتدبير الخراجات وتقييم الحالات السنية العاجلة.</span></div></div></section><section class="profile-section"><h2>التعليم والخلفية المهنية</h2><ul class="qualification-list"><li>دكتور في جراحة الأسنان DDS من جامعة عجمان</li><li>برنامج امتياز طب الأسنان، جامعة عجمان</li><li>دبلوم في طب الأسنان التجميلي المتقدم، Mastery Academy، دبي</li><li>تدريب إضافي ضمن Fellowship in Successful Endodontic Practice بإشراف أ.د. طلال النحلاوي</li></ul></section><section class="profile-section"><h2>اللغات ونهج الرعاية</h2><p>تتحدث د. سارة العربية والإنجليزية، وتركز على التواصل الواضح وراحة المريض ووضع خطط علاج تراعي الاحتياجات السريرية للبالغين والأطفال.</p></section><section class="profile-section"><h2>الرعاية ذات الصلة</h2><div class="profile-treatment-links"><a class="profile-treatment-link" href="../treatments/cosmetic-dentistry.html">طب الأسنان التجميلي <span>→</span></a><a class="profile-treatment-link" href="../treatments/general-dentistry.html">طب الأسنان العام <span>→</span></a><a class="profile-treatment-link" href="../treatments.html">عرض العلاجات <span>→</span></a></div></section>'
    },
}

for path, data in EN.items():
    update_profile(path, data["intro"], data["body"], data["meta"])
for path, data in AR.items():
    update_profile(path, data["intro"], data["body"], data["meta"])

# Replace Dr. Ehab's old portrait references with the new optimized portrait.
for rel in ["doctors/dr-ehab-hassouneh.html", "ar/doctors/dr-ehab-hassouneh.html", "doctors.html", "ar/doctors.html"]:
    p = ROOT / rel
    text = p.read_text(encoding="utf-8")
    text = text.replace("dr-ehab-new%20(2).png", "dr-ehab-new-v2.webp")
    text = text.replace("dr-ehab-new (2).png", "dr-ehab-new-v2.webp")
    p.write_text(text, encoding="utf-8")

for path, name, focus in [
    ("doctors.html", "Dr. Kashmira Pawar Jayprakash", "Pediatric dentistry focused on prevention, restorative care, pulp therapy and age-appropriate support for children."),
    ("doctors.html", "Dr. Nasr Keshkiea", "General dentistry with interests in restorative care, prosthodontic rehabilitation, endodontics and aesthetic treatment."),
    ("doctors.html", "Dr. Ehab Hassouneh Bassam A", "General dentistry with interests in restorative, digital, pediatric and preventive dental care."),
    ("doctors.html", "Dr. Nachiket Shah", "Specialist periodontal care with implant privilege, tissue regeneration and selected laser-assisted procedures."),
    ("doctors.html", "Dr. Sara Ismail", "General dentistry with interests in restorative and aesthetic care, endodontics, pediatric dentistry and prevention."),
    ("ar/doctors.html", "Dr. Kashmira Pawar Jayprakash", "طب أسنان الأطفال مع التركيز على الوقاية والترميم وعلاج اللب والرعاية المناسبة لعمر الطفل."),
    ("ar/doctors.html", "Dr. Nasr Keshkiea", "طب الأسنان العام مع اهتمام بالترميم والتعويضات السنية وعلاج الجذور والعلاجات التجميلية."),
    ("ar/doctors.html", "Dr. Ehab Hassouneh Bassam A", "طب الأسنان العام مع اهتمام بالعلاجات الترميمية والرقمية ورعاية الأطفال والوقاية."),
    ("ar/doctors.html", "Dr. Nachiket Shah", "رعاية متخصصة للثة مع امتياز زراعة الأسنان وتجديد الأنسجة وإجراءات مختارة بمساعدة الليزر."),
    ("ar/doctors.html", "Dr. Sara Ismail", "طب الأسنان العام مع اهتمام بالترميم والتجميل وعلاج الجذور ورعاية الأطفال والوقاية."),
]:
    update_directory_card(path, name, focus)

print("Doctor profile content refresh applied")
